# Java CI/CD with Maven DockerHub Google Artifact Registry and Google Cloud Run
name: Java CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_NAME: debit-wallet
  DOCKERHUB_IMAGE_NAME: ricardomaximino/debit-wallet:latest

jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: google
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 25
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '25'
        distribution: 'graalvm'
        cache: maven
    - name: Build with Maven
      run: mvn package

    - name: Build the Docker image
      run: docker build . --tag ${DOCKERHUB_IMAGE_NAME}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image to Docker Hub
      run: docker push ${DOCKERHUB_IMAGE_NAME}

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Configure Docker to use Google Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

    - name: Tag and Push Docker Image to Google Artifact Registry
      run: |
        # The full image name for Artifact Registry
        FULL_GCR_IMAGE=${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/${IMAGE_NAME}:latest
        docker tag ${DOCKERHUB_IMAGE_NAME} $FULL_GCR_IMAGE
        docker push $FULL_GCR_IMAGE
        
        # Make the full image name available for the next step
        echo "FULL_GCR_IMAGE=$FULL_GCR_IMAGE" >> $GITHUB_ENV

    - name: Deploy to Google Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ secrets.CLOUD_RUN_SERVICE }}
        region: ${{ secrets.REGION }}
        image: ${FULL_GCR_IMAGE}
